### ISSUE TITLE
How to install this from Local

### ISSUE THREAD

**Issue by shivapoudel** [pixeljar/local-addon-xdebug-vscode#1]
There is an option in Local to install the add-on from disk. Can you make a release in this repo so we can download the production version and install instead of cloning and installing dependencies?

**Comment by brandondove** [comment]
@shivapoudel Thanks for the suggestion. I've included the compiled version in the repo and tagged version 1.0 so you can download and install it.

**Comment by shivapoudel** [comment]
I have downloaded the zip and place it in the directory, but to install from local UI tar far is recommended so you can attach the release asset too.. 

Next thing whenever I activate the addon I see relaunch notice always after relaunch too

![image](https://user-images.githubusercontent.com/3774827/85603570-35987e00-b670-11ea-9d7d-93cad77b57cf.png)

**Comment by brandondove** [comment]
@shivapoudel It looks like Local's install from disk functionality is broken at the moment. I'm not able to replicate the relaunch notice issue in your screenshot. When I activate it, I get that message. But when I click the relaunch button and the app closes and reopens, I no longer see the relaunch message.
