### ISSUE TITLE
git clone and yarn install is failing

### ISSUE THREAD

**Issue by claytoncollie** [pixeljar/local-addon-xdebug-vscode#2]
change directories into Local/addons, ran a git clone, then `yarn install`. Got these error messages. Running on macOS. Local 5.6.1+4184

```
> local-addon-xdebug-vscode@1.0.0 build /Users/claytoncollie/Library/Application Support/Local/addons/local-addon-xdebug-vscode
> tsc

node_modules/@getflywheel/local/main.d.ts:870:16 - error TS2304: Cannot find name 'ConnectDirection'.

870  			direction: ConnectDirection,
     			           ~~~~~~~~~~~~~~~~

node_modules/@getflywheel/local/main.d.ts:871:21 - error TS2304: Cannot find name 'FlywheelSite'.

871  			flywheelSiteID: FlywheelSite['id'],
     			                ~~~~~~~~~~~~

node_modules/@getflywheel/local/main.d.ts:872:18 - error TS2304: Cannot find name 'flywheelSiteEnvironment'.

872  			environment: flywheelSiteEnvironment,
     			             ~~~~~~~~~~~~~~~~~~~~~~~
````

**Comment by brandondove** [comment]
@claytoncollie I did run into that as well, and I think it's because I'm missing a package. I'm tracking it down, but in the meantime, I've added the compiled version of this add-on to the repo and tagged version 1.0 so you can just download the compiled version and drop it into the Local/addons folder.

**Comment by brandondove** [comment]
@claytoncollie I've opened a discussion on the Local community forums to see if others are having this issue as well. https://localwp.com/community/t/getflywheel-local-errors-during-build/20439.

**Comment by brandondove** [comment]
@claytoncollie we've pushed an update that fixes this compiling issue (https://github.com/pixeljar/local-addon-xdebug-vscode/releases/tag/1.0.1) Additionally, Local has included this in the app as a core add-on so you can now get this add-on from there (https://localwp.com/add-ons/ or within the new version of the app).
