### ISSUE TITLE
Unable to enable on Windows

### ISSUE THREAD

**Issue by ChuckMac** [pixeljar/local-addon-xdebug-vscode#26]
Trying to enable the extension on Windows copy of Local (6.1.5+5536) and getting the following error:

**Error: Cannot find module 'uuid/v4'**

```{"thread":"main","class":"AddonLoaderService","stack":"Error: Cannot find module 'uuid/v4'\nRequire stack:\n- %%userDataPath%%\\addons\\local-addon-xdebug-vscode\\lib\\main.js\n- %%appPath%%\\main\\addons\\AddonLoaderService.js\n- %%appPath%%\\main\\serviceContainer.js\n- %%appPath%%\\main\\main.js\n- \n    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)\n    at Function.n._resolveFilename (electron/js2c/browser_init.js:261:1128)\n    at Function.Module._resolveFilename (%%appPath%%\\node_modules\\module-alias\\index.js:49:29)\n    at Module._load (internal/modules/cjs/loader.js:732:27)\n    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)\n    at Module.require (internal/modules/cjs/loader.js:959:19)\n    at require (internal/modules/cjs/helpers.js:88:18)\n    at Object.<anonymous> (%%userDataPath%%\\addons\\local-addon-xdebug-vscode\\lib\\main.js:35:30)\n    at Module._compile (internal/modules/cjs/loader.js:1078:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)","level":"error","message":"Error Loading Add-on: %%userDataPath%%\\addons\\local-addon-xdebug-vscode\\lib\\main.js","timestamp":"2021-10-22T13:02:21.350Z"}```

**Comment by brandondove** [comment]
@ChuckMac I have finally had some time to look at this PR and merged it in. I am sure there are probably even more updates to be done here, so this may not fix this for everyone just yet. I'll be looking at this add-on to see what else can be improved as well.
