### ISSUE TITLE
Update LocalWP compatibility info

### ISSUE THREAD

**Issue by TonyGravagno** [pixeljar/local-addon-xdebug-vscode#31]
The [LocalWP addon page](https://localwp.com/add-ons/xdebug-vscode/) for this plugin shows "Tested Up To 5.10.0". Since Local is now at v6.2.1 and the addon obviously works, perhaps this should be updated.

**Comment by bgturner** [comment]
Hey @TonyGravagno -- Thanks for the heads up!

I'll be releasing a new version of this addon soon (maybe next week due to the holiday) and will be sure to bump that version!


Relates to: #42

**Comment by brandondove** [comment]
I just merged the PR @bgturner.
