### ISSUE TITLE
Installed launch configuration seems different from what I've been using for years

### ISSUE THREAD

**Issue by afragen** [pixeljar/local-addon-xdebug-vscode#5]
@brandondove not certain it makes a difference but here's what I have for my launch config.

```json
"launch": {
		"version": "0.2.0",
		"configurations": [
			{
				"name": "Listen for xDebug (Local 5.x)",
				"type": "php",
				"request": "launch",
				"port": 9000,
				"pathMappings": {
					"": "${workspaceFolder}"
				},
				"xdebugSettings": {
					"max_children": 128,
					"max_data": 1024,
					"max_depth": 3,
					"show_hidden": 1
				}
			},
			{
				"name": "Launch currently open script",
				"type": "php",
				"request": "launch",
				"program": "${file}",
				"cwd": "${fileDirname}",
				"port": 9000
			},
			{
				"name": "Listen for xDebug (Local 3.x)",
				"type": "php",
				"request": "launch",
				"port": 9000,
				"pathMappings": {
					"/app/public": "${workspaceFolder}"
				},
				"xdebugSettings": {
					"max_children": 128,
					"max_data": 1024,
					"max_depth": 3,
					"show_hidden": 1
				}
			
		]
	},

```

The additional `xdebugSettings` help to display more data in the variables, etc.
 
I have also included my xDebug launch settings for Local 3.x.

This works for me when VSCode is opening the `/app/public` directory.

**Comment by brandondove** [comment]
@afragen have you tried using the config supplied by the add-on? Is it not working for you? Are the extra XDebug settings worth adding to the add-on?

**Comment by afragen** [comment]
@brandondove I’ll have to give the plugin a try. I confess to having had this setup for a couple of years now and I have it setup globally, not per project.

I found the extra settings needed if you have variables with many components.

**Comment by afragen** [comment]
Hey Brandon,

https://xdebug.org/docs/dbgp#id45
https://xdebug.org/docs/all_settings

I've had a chance to utilize the plugin and it's awesome. 

I believe the default values for `max_children` and `max_depth` in my example are actually the default values and not necessary. The default value for `max_data` is 512. This is the amount of data displayed of the variable's value. `show_hidden` will display private class members, it's probably the only extra setting that should be present as I think it allows for displaying things like private variables, but I'm not certain.

Keep up the great work.

**Comment by brandondove** [comment]
@afragen, thanks for the clarification. I went ahead and added `max_data` and `show_hidden` to the config file set up and tagged a new release. Let me know if you have any other feedback.

**Comment by afragen** [comment]
Thanks Brandon. Now I'm curious as to how the plugin updates.

**Comment by afragen** [comment]
@brandondove I was just doing some testing and I think you'll need to add `max_childern` and `max_depth` to the `extraSettings`. It almost behaves as if when `extraSettings` are listed these end up not being defined.

To see what I mean just look into an object containing arrays and look into one of the arrays.

**Comment by brandondove** [comment]
I've added those setting and tagged a new release. As for your question about receiving updates for these, I don't think there's a mechanism for that. At least not one that I've seen. You'll probably just have to pull a new version down from this repo.

**Comment by afragen** [comment]
If there's a way to update the repo as it exists in Flywheel's repository then the user can uninstall from the Active plugins tab and re-install the newer verison. Given the experience of users that might be the best option. 😉

**Comment by brandondove** [comment]
Yeh, that would be ideal. The process of getting that add-on listed in the add-ons tab seemed pretty manual though. I'll reach out and see what options are available.

**Comment by afragen** [comment]
Interesting, I'm having difficulty using the 'Install from disk option' in the Installed Add-ons pane. I sent a priority support. We'll see, but given the tech experience of the forum users I would think simpler is better. 😉

**Comment by afragen** [comment]
I don't think the latest release is completely built, no node_modules

**Comment by brandondove** [comment]
Yeh, I saw the post in the forums that you were involved in where installing from disk is broken. I've had the same experience when I was building this in the first place. I think that feature is still broken in Local.

**Comment by brandondove** [comment]
> I don't think the latest release is completely built, no node_modules

@afragen You're right. I should probably create an archive with everything so folks can just download that.

**Comment by afragen** [comment]
Interesting, the latest release as a tar.gz file is recognized by the 'Add from disk' but I get the following error.

<img width="420" alt="screenshot_106" src="https://user-images.githubusercontent.com/1296790/87192314-14a86d80-c2ab-11ea-8086-cd2451711033.png">

I zipped up the folder and a zip file isn't recognized by the 'Add for disk' dialog.

Decompressing and adding to the `addons` folder, restart, etc does make 1.0.6 correctly function.

**Comment by afragen** [comment]
So here's what worked. I got from Ben at Flywheel.

Taking the release asset `.tar.gz` download run the following command from within the parent folder.

`tar xzf local-addon-xdebug-vscode.tar.gz && cd local-addon-xdebug-vscode && npm run build && npm pack`

This creates a `.tgz` file inside of the `local-addon-xdebug-vscode` folder. Use that `.tgz` file with Install Add-on.

You should use this `.tgz` file as your release asset.

**Comment by brandondove** [comment]
Good to know. I've updated the release with a .tgz file using the commands above.
